apiVersion: v1
kind: Service
metadata:
  name: news-backend
  namespace: istio-demo
  labels:
    app: news-backend
    service: news-backend
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: news-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: news-backend
  namespace: istio-demo
  labels:
    account: news-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend-v1
  namespace: istio-demo
  labels:
    app: news-backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-backend
      version: v1
  template:
    metadata:
      labels:
        app: news-backend
        version: v1
    spec:
      serviceAccountName: news-backend
      containers:
        - name: news-backend
          image: docker.io/smojum/pega-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: news-backend-v2
#   namespace: istio-demo
#   labels:
#     app: news-backend
#     version: v2
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: news-backend
#       version: v2
#   template:
#     metadata:
#       labels:
#         app: news-backend
#         version: v2
#     spec:
#       serviceAccountName: news-backend
#       containers:
#         - name: news-backend
#           image: docker.io/smojum/pega-backend:latest
#           imagePullPolicy: IfNotPresent
#           env:
#             - name: SERVER_PORT
#               value: "8080"
#           ports:
#             - containerPort: 8080            